---
- hosts: all
  become: true


  tasks: 
  
  - name: update repository index
    apt:
      update_cache: yes 
    

  - name: install apache2 package on redhat and debian/ubuntu
    apt:
      name: apache2
      state: absent  


  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: absent


  - name: update repository index for dnf
    dnf:
      update_cache: yes


  - name: install httpd package for redhat
    dnf:
      name: httpd    
      state: absent

  - name: install php support for httpd

    dnf:
      name: libapache2-mod-php
      state: absent




...
