---                                            # keep al servers up-to-date first
- hosts: all
  become: true
  pre_tasks: 
  - name: install udates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package: 
      name: unzip

    - name: install terraform    
      unarchive: 
        src: https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root


- hosts: web_servers                        # install apache2 and php on ubuntu hosts that are webservers
  become: true
  tasks:  

  - name: install apache2, nginx, rkhunter, chkrootkit, lynis, mrtg and php on ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - nginx 
        - rkhunter
        - chkrootkit
        - lynis
        - mrtg  
      state: latest 
    when: ansible_distribution in ["Ubuntu"]


  - name: install httpd, nginx, rkhunter, lynis, mrtg and php packages for CentOS
    tags: apache,centos,httpd 
    dnf:                                    # install httpd and php on centos hosts that are webservers
      name: 
        - httpd
        - php    
        - nginx  
        - rkhunter  
        - lynis
        - mrtg    
      state: latest
    when: ansible_distribution == "CentOS"  

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes     # apache will start after reboot   
    when: ansible_distribution == "CentOS"

  - name: change email-address for admin
    tags: apache,centos,httpd
    lineinfile:      # allows to change a line in a file 
      path: /etc/httpd/conf/httpd.conf  #path to the file you want to edit
      regexp: '^ServerAdmin'  # edit a line that begins with ServerAdmin
      line: ServerAdmin ulrich.kleemann@bechtle.com # change it to this e-mail address
    when: ansible_distribution == "CentOS" # but do this only, if the host runs on CentOS
    register: httpd # store the changes in a variable called httpd 


  - name: restart httpd (CentOS) # restart apache
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed # but only if the variable httpd contains a changed statement

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:  
      src: default_site.html 
      dest: /var/www/html/index.html  
      owner: root
      group: root
      mode: 0644 



- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb_package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: install mariadb_package (Ubuntu)
    tags: db,mariadb,ubuntu 
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb_package (Debian)
    tags: debian,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba_package
    tags: samba
    dnf:
      name: samba
      state: latest
    when: ansible_distribution == "CentOS"
 
- hosts: test_servers
  become: true
  tasks:
  - name: install podman_package
    tags: podman
    dnf:
      name: podman
      state: latest
    when: ansible_distribution == "CentOS"    
        
  - name: install fail2ban_package
    tags: fail2ban
    dnf:
      name: fail2ban
      state: latest
    when: ansible_distribution == "CentOS"


  - name: install rkhunter_package
    tags: rkhunter
    dnf:
      name: rkhunter
      state: latest 
    when: ansible_distribution == "CentOS"


  - name: install vim_package
    tags: vim
    dnf:
      name: vim
      state: latest
    when: ansible_distribution == "CentOS"


- hosts: mail_servers
  tags: postfix
  become: true
  tasks:
  - name: install postfix_package
    dnf:
      name: postfix
      state: latest
    when: ansible_distribution == "Centos"    

  - name: install dovecot_package
    tags: dovecot    
    dnf:
      name: dovecot
      state: latest
    when: ansible_distribution == "CentOS"


  - name: install vim_package
    tags: vim
    dnf:
      name: vim
      state: latest
    when: ansible_distribution == "CentOS"    




...

