---                                            # keep al servers up-to-date first
- hosts: all
  become: true
  pre_tasks: 
  - name: install udates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: configure dns entries
    tags: apache,centos,ubuntu,httpd
    lineinfile:      # allows to change a line in a file 
      path: /etc/resolv.conf  #path to the file you want to edit
      regexp: '^nameserver'  # edit a line that begins with nameserver
      line: nameserver 8.8.8.8, 92.60.37.213 # change it to this e-mail address
        #when: ansible_distribution == "CentOS" # but do this only, if the host runs on CentOS
    register: dns # store the changes in a variable called dns



  tasks:

  - name: create uli  user
    tags: always
    user: 
      name: uli
      groups: root

  - name: add ssh key for uli
    tags: always
    authorized_key:
      user: uli
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBX/R/uxuI+C2ZUjNoFM8saZy/PRi2aP7jhagEpSSrFv ansible@bechtle
"

  - name: add sudoers file for uli
    copy:
      #src: sudoer_uli
      content: "uli ALL=(ALL) NOPASSWD:ALL"
      dest: /etc/sudoers.d/uli
      owner: root
      group: root
      mode: 0440
        





...

